version: '3'

services:
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db
    ports:
      - "55432:5432"
  redis:
    image: "redis:alpine"
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn TinPennyBackend.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 8000
    depends_on:
      - db
      - redis
    env_file: .env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
  celery:
    build: ./app
    command: celery -A TinPennyBackend worker -l info
    volumes:
      - ./app:/code
    depends_on:
      - db
      - redis
    environment:
      - SECRET_KEY=foobar

volumes:
  postgres_data:
  static_volume: